// Endpoints + catalog styling for the AI-first PhilSA webmap.
// Override any of these at build time with a VITE_* env var (see .env.example).

export const STAC_API =
  import.meta.env.VITE_STAC_API ?? "http://localhost:8082";

// TiTiler — dynamic raster tiler for the silver COGs (compose.viz.yml, port 8083).
export const TITILER =
  import.meta.env.VITE_TITILER ?? "http://localhost:8083";

// Public R2 base that serves the admin-boundary PMTiles, MosaicJSON and COGs.
export const R2_PUBLIC_BASE =
  import.meta.env.VITE_R2_PUBLIC_BASE ??
  "https://pub-17ab60a2ca7142a48ae8e2685cd853f7.r2.dev";

// Chat backend (server/chat.mjs). Vite proxies /api → :8087 in dev.
export const CHAT_API = import.meta.env.VITE_CHAT_API ?? "/api/chat";

// STAC Browser explorer UI (compose.viz.yml, port 8080). Collection pages are
// path-routed (historyMode: "history" in stac-browser/config.js), so the
// dataset page for a collection is simply /collections/<id>.
export const STAC_BROWSER =
  import.meta.env.VITE_STAC_BROWSER ?? "http://localhost:8080";

export const stacBrowserCollectionUrl = (collection: string): string =>
  `${STAC_BROWSER}/collections/${collection}`;

// Name→bbox index of PH admin units (adm0–adm3), generated by the dashboard's
// build_admin_search_index.py and hosted on public R2. Reused here as the
// lookup behind the AI's resolve_region tool.
export const ADMIN_INDEX_URL = `${R2_PUBLIC_BASE}/02-silver/ph-admin-boundaries/ph_admin_index.json`;

const PMTILES_PREFIX = "02-silver/ph-admin-boundaries/pmtiles";
const SILVER_PREFIX = "02-silver";

// Public R2 URL of the per-date MosaicJSON for a raster collection. Built by
// `pipelines/02-silver/build_raster_mosaics.sh`; each one stitches a single
// day's COG granules into a seamless layer TiTiler serves via /mosaicjson.
// Not every collection has mosaics (flood doesn't yet) — callers must fall
// back to per-item COG tiles when this 404s. `date` is YYYY-MM-DD.
export function mosaicJsonUrl(collection: string, date: string): string {
  return `${R2_PUBLIC_BASE}/${SILVER_PREFIX}/${collection}/mosaics/${collection}_${date}.mosaicjson`;
}

// Legend for the layer panel. A `ramp` is a continuous gradient bar (with end
// labels) for rescaled single-band layers; `classes` is a swatch list for a
// categorical layer. Colours must mirror the TiTiler styling in `titilerParams`.
export type Legend =
  | { kind: "ramp"; stops: string[]; minLabel: string; maxLabel: string }
  | { kind: "classes"; items: { color: string; label: string }[] };

// Admin-boundary vector overlays (PMTiles on R2), pre-seeded into the layer
// store at startup so both the panel and the AI can toggle them.
export interface AdminLayerDef {
  id: string;
  label: string;
  sourceLayer: string;
  pmtilesUrl: string; // pmtiles:// URL
  color: string;
  width: number;
  minzoom?: number;
  defaultOn: boolean;
}

export const ADMIN_LAYERS: AdminLayerDef[] = [
  {
    id: "adm0",
    label: "Country outline (adm0)",
    sourceLayer: "adm0",
    pmtilesUrl: `pmtiles://${R2_PUBLIC_BASE}/${PMTILES_PREFIX}/phl_adm0.pmtiles`,
    color: "#1a237e",
    width: 1.6,
    defaultOn: true,
  },
  {
    id: "adm1",
    label: "Regions (adm1)",
    sourceLayer: "adm1",
    pmtilesUrl: `pmtiles://${R2_PUBLIC_BASE}/${PMTILES_PREFIX}/phl_adm1.pmtiles`,
    color: "#3949ab",
    width: 1.0,
    defaultOn: true,
  },
  {
    id: "adm2",
    label: "Provinces (adm2)",
    sourceLayer: "adm2",
    pmtilesUrl: `pmtiles://${R2_PUBLIC_BASE}/${PMTILES_PREFIX}/phl_adm2.pmtiles`,
    color: "#7986cb",
    width: 0.6,
    minzoom: 5,
    defaultOn: true,
  },
  {
    id: "adm3",
    label: "Municipalities (adm3)",
    sourceLayer: "adm3",
    pmtilesUrl: `pmtiles://${R2_PUBLIC_BASE}/${PMTILES_PREFIX}/phl_adm3.pmtiles`,
    color: "#9fa8da",
    width: 0.5,
    minzoom: 7,
    defaultOn: false,
  },
  {
    id: "adm4",
    label: "Barangays (adm4)",
    sourceLayer: "adm4",
    pmtilesUrl: `pmtiles://${R2_PUBLIC_BASE}/${PMTILES_PREFIX}/phl_adm4.pmtiles`,
    color: "#c5cae9",
    width: 0.4,
    minzoom: 9,
    defaultOn: false,
  },
];

// Raster (COG) collections served through TiTiler. Items are discovered from
// the STAC API at runtime; `titilerParams` controls styling and must stay in
// step with the `renders` metadata in pipelines/03-gold/catalog_silver.py.
export interface RasterDef {
  id: string; // == STAC collection id
  label: string;
  titilerParams: string; // extra query string for the tiler (no leading &)
  description: string; // one-line plain-language summary
  legend?: Legend;
  // Per-acquisition-date collections (true) render one date at a time (mosaic
  // if present, per-item COGs otherwise). Date-independent collections (false,
  // e.g. annual LULC) render all their COGs at once.
  temporal: boolean;
  // Unit label for zonal means of this collection (time-series window average
  // + CSV export). Only single-band physical/index layers get one — RGB and
  // categorical layers omit it, which hides the averaging UI for them.
  statsUnit?: string;
}

export const RASTER_DEFS: RasterDef[] = [
  {
    id: "sentinel2-truecolor",
    label: "Natural-Colour Satellite Imagery",
    // 8-bit RGB TCI COG — TiTiler auto-detects the 3 bands.
    titilerParams: "",
    temporal: true,
    description:
      "Natural-colour optical view (Sentinel-2, 10 m). Land and clouds as the eye would see them; daylight only.",
  },
  {
    id: "sentinel2-ndvi",
    label: "Vegetation Health (NDVI)",
    // single-band float32 — needs a stretch + colormap or it renders black.
    titilerParams: "rescale=-0.2,0.9&colormap_name=rdylgn",
    temporal: true,
    statsUnit: "NDVI",
    description:
      "Vegetation greenness index (Sentinel-2). Green = dense/healthy vegetation, red = bare soil or water.",
    legend: {
      kind: "ramp",
      stops: [
        "#a50026", "#d73027", "#f46d43", "#fdae61", "#fee08b", "#ffffbf",
        "#d9ef8b", "#a6d96a", "#66bd63", "#1a9850", "#006837",
      ],
      minLabel: "−0.2 · bare / water",
      maxLabel: "dense veg · 0.9",
    },
  },
  {
    id: "sentinel1-sar",
    label: "All-Weather Radar Imagery",
    // single-band float32 VV backscatter (dB) — grayscale; rescale ≈ mean ±2σ.
    // NoData (-9999) is declared in the COG, so TiTiler masks it automatically.
    titilerParams: "rescale=20,52",
    temporal: true,
    statsUnit: "dB (VV)",
    description:
      "Radar backscatter (Sentinel-1 VV, grayscale). Sees through cloud, day or night; bright = rough/built-up, dark = smooth/water.",
    legend: {
      kind: "ramp",
      stops: ["#000000", "#ffffff"],
      minLabel: "20 dB · smooth / water",
      maxLabel: "rough / built · 52 dB",
    },
  },
  {
    id: "sentinel1-ratio",
    label: "Radar Vegetation Index (VH/VV)",
    // single-band float32 cross-ratio in dB — needs a stretch + colormap.
    // Colourblind-safe sequential ramp: pale = bare/water, dark green = canopy.
    // stretch = p2–p98 of the first built scene (2026-07-07): −13.9…−2.4 dB.
    titilerParams: "rescale=-14,-2&colormap_name=ylgn",
    temporal: true,
    statsUnit: "dB (VH/VV)",
    description:
      "Radar vegetation index (Sentinel-1 VH/VV ratio, dB). Rises with crop canopy growth and sees through cloud — NDVI's wet-season sibling. Index layer, not a calibrated crop product.",
    legend: {
      kind: "ramp",
      stops: [
        "#ffffe5", "#f7fcb9", "#d9f0a3", "#addd8e", "#78c679", "#41ab5d",
        "#238443", "#006837", "#004529",
      ],
      minLabel: "−14 dB · bare / water",
      maxLabel: "dense canopy · −2 dB",
    },
  },
  {
    id: "sentinel1-flood",
    label: "Flood Extent (radar-derived)",
    // Byte mask: 1=water, 2=permanent water, 0=land, 255=nodata. Discrete
    // colormap (only water classes coloured; land left transparent) matching
    // the `flood` render in catalog_silver.py.
    titilerParams: `colormap=${encodeURIComponent(
      JSON.stringify({
        "1": [33, 102, 204, 255], // detected water / flood
        "2": [120, 170, 230, 255], // permanent water
      }),
    )}`,
    temporal: true,
    description:
      "Open-water / flood mask derived from Sentinel-1 radar. POC proxy — NOT a validated flood product; pair with Copernicus EMS/GFM for anything real.",
    legend: {
      kind: "classes",
      items: [
        { color: "#2166CC", label: "Detected water / flood" },
        { color: "#78AAE6", label: "Permanent water" },
      ],
    },
  },
  {
    id: "esri-10m-lulc",
    label: "ESRI Land Cover (10 m, 2025)",
    // Categorical uint8 class codes — needs a DISCRETE colormap (class → RGBA),
    // not rescale + colormap_name. Impact Observatory 9-class palette; nodata=0
    // is declared in the COG so TiTiler masks tile overlap automatically.
    titilerParams: `colormap=${encodeURIComponent(
      JSON.stringify({
        "1": [26, 91, 171, 255], // Water
        "2": [53, 130, 33, 255], // Trees
        "4": [135, 209, 158, 255], // Flooded vegetation
        "5": [255, 219, 92, 255], // Crops
        "7": [237, 2, 42, 255], // Built area
        "8": [237, 233, 228, 255], // Bare ground
        "9": [242, 250, 255, 255], // Snow/ice
        "10": [200, 200, 200, 255], // Clouds
        "11": [198, 173, 141, 255], // Rangeland
      }),
    )}`,
    temporal: false,
    description:
      "Annual land-cover classes (Impact Observatory, 10 m, 2025): water, trees, crops, built-up, bare, rangeland. Context layer, not ground truth.",
    legend: {
      kind: "classes",
      items: [
        { color: "#1A5BAB", label: "Water" },
        { color: "#358221", label: "Trees" },
        { color: "#87D19E", label: "Flooded veg." },
        { color: "#FFDB5C", label: "Crops" },
        { color: "#ED022A", label: "Built area" },
        { color: "#EDE9E4", label: "Bare ground" },
        { color: "#C6AD8D", label: "Rangeland" },
        { color: "#F2FAFF", label: "Snow / ice" },
        { color: "#C8C8C8", label: "Clouds" },
      ],
    },
  },
];

export const rasterDef = (collection: string): RasterDef | undefined =>
  RASTER_DEFS.find((r) => r.id === collection);

// Initial view: Luzon, where the S2 true-colour / NDVI coverage overlaps.
export const INITIAL_VIEW = {
  longitude: 121.6,
  latitude: 16.2,
  zoom: 6.2,
};
